site_name: 技术备忘录
site_url: https://kuoihao.github.io/blog/
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.select
    - content.code.copy
    - content.code.annotate 
    - navigation.indexes
    # - navigation.tabs


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - blog
  - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Blog:
     - blog/index.md
  - Llama:
    - Llama/index.md
    - Llama/llama.cpp.md
    - Llama/2410.03613.md
    - Llama/代码操作手册.md
    - Llama/问题问答.md
    - Llama/llama.cpp源码解读.md
    - Llama/配置一个干净的安卓开发环境.md
    - Llama/如何检测设备是否支持sve特性.md
    - Llama/观察可能的研究方向.md